services:
  frontend:
    build:
      context: ./front
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back/api:/app/api
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

